#!/bin/bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}       Trivy Security Scanner${NC}"
echo -e "${BLUE}=========================================${NC}"

# Check if image name is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <docker-image-name>"
    echo "Example: $0 nginx:1.18.0"
    exit 1
fi

IMAGE_NAME=$1
REPORT_DIR="./reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
JSON_REPORT="$REPORT_DIR/trivy_${IMAGE_NAME//[\/:]/_}_${TIMESTAMP}.json"
HTML_REPORT="$REPORT_DIR/trivy_${IMAGE_NAME//[\/:]/_}_${TIMESTAMP}.html"

mkdir -p "$REPORT_DIR"

echo -e "${YELLOW}Scanning image: $IMAGE_NAME${NC}"
echo -e "${YELLOW}Reports will be saved in: $REPORT_DIR${NC}"

# Run Trivy scan
echo -e "\n${GREEN}[1/3] Running vulnerability scan...${NC}"
trivy image --format json --output "$JSON_REPORT" --severity HIGH,CRITICAL "$IMAGE_NAME"

echo -e "\n${GREEN}[2/3] Generating summary...${NC}"

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}jq not installed. Installing...${NC}"
    sudo apt install -y jq
fi

if [ -f "$JSON_REPORT" ]; then
    TOTAL_VULNS=$(jq '.Results[].Vulnerabilities | length' "$JSON_REPORT" 2>/dev/null | awk '{sum+=$1} END {print sum}')
    CRITICAL_VULNS=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "CRITICAL")] | length' "$JSON_REPORT" 2>/dev/null || echo "0")
    HIGH_VULNS=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH")] | length' "$JSON_REPORT" 2>/dev/null || echo "0")
else
    TOTAL_VULNS=0
    CRITICAL_VULNS=0
    HIGH_VULNS=0
fi

echo -e "\n${BLUE}=== Scan Results ===${NC}"
echo -e "Image: ${YELLOW}$IMAGE_NAME${NC}"
echo -e "Total vulnerabilities: ${YELLOW}${TOTAL_VULNS:-0}${NC}"
echo -e "Critical vulnerabilities: ${RED}${CRITICAL_VULNS:-0}${NC}"
echo -e "High vulnerabilities: ${YELLOW}${HIGH_VULNS:-0}${NC}"

# Simple HTML report
echo -e "\n${GREEN}[3/3] Creating HTML report...${NC}"
cat > "$HTML_REPORT" << HTML
<!DOCTYPE html>
<html>
<head>
    <title>Trivy Security Scan Report - $IMAGE_NAME</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
        .summary { background: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0; }
        .critical { color: #e74c3c; font-weight: bold; }
        .high { color: #e67e22; }
        .medium { color: #f1c40f; }
        .low { color: #3498db; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔒 Trivy Security Scan Report</h1>
            <p>Image: $IMAGE_NAME</p>
            <p>Scan date: $(date)</p>
        </div>
        
        <div class="summary">
            <h2>📊 Scan Summary</h2>
            <p><strong>Total Vulnerabilities:</strong> ${TOTAL_VULNS:-0}</p>
            <p class="critical">Critical: ${CRITICAL_VULNS:-0}</p>
            <p class="high">High: ${HIGH_VULNS:-0}</p>
        </div>
        
        <h2>📋 Detailed Results</h2>
        <p>Scan completed successfully. For detailed JSON report, check: $(basename "$JSON_REPORT")</p>
        
        <h3>🔍 Top Vulnerabilities:</h3>
        <pre>
$(trivy image --format table --severity HIGH,CRITICAL "$IMAGE_NAME" | head -20)
        </pre>
        
        <h3>📈 Recommendations:</h3>
        <ul>
            <li>Update to latest base image version</li>
            <li>Remove unnecessary packages</li>
            <li>Implement security scanning in CI/CD pipeline</li>
            <li>Regularly update dependencies</li>
        </ul>
        
        <footer style="margin-top: 50px; padding: 20px; background: #ecf0f1; border-radius: 5px;">
            <p>Generated by DevSecOps Project - Engineering Thesis</p>
        </footer>
    </div>
</body>
</html>
HTML

# Check if there are critical vulnerabilities
if [ "${CRITICAL_VULNS:-0}" -gt 0 ]; then
    echo -e "\n${RED}❌ CRITICAL VULNERABILITIES DETECTED!${NC}"
    echo -e "${RED}The image contains $CRITICAL_VULNS critical security issues.${NC}"
    echo -e "${RED}Please review the report at: $HTML_REPORT${NC}"
    exit 1
else
    echo -e "\n${GREEN}✅ No critical vulnerabilities detected.${NC}"
    echo -e "${GREEN}Detailed report: $HTML_REPORT${NC}"
fi

echo -e "\n${GREEN}Scan completed successfully!${NC}"
